### ISSUE TITLE
add downstream port

### ISSUE THREAD

**Issue by chaseadam** [antmicro/thunderbolt-pcie-adapter#3] opened 2023-09-06 21:50 UTC
I would like to also break out the downstream port (even it if has to share the bandwidth), so may contribute that back. Keep feature request here to track if anyone gets to it before me.

**Comment by pgielda** [comment] 2023-09-07 08:13
The issue tracker is meant to file bugs and issues with the board. This seems to be more of a feature request... But its not a bug, it was meant to not have a downstream port. We might at some point create a different board that has one (or you can create your own board), but I am closing this as its not a bug.

**Closed as not planned by pgielda** 2023-09-07 08:13 UTC

**Comment by chaseadam** [comment] 2023-09-07 13:16
thanks for the clarity, yep, more of a feature request.
